language: python
python:
 - "2.7"
 - "3.6"
env:
 - FLASK_VERSION=0.8
 - FLASK_VERSION=0.9
 - FLASK_VERSION=0.10
 - FLASK_VERSION=0.12
install:
 - "pip install -r requirements.txt"
 - "pip install -I Flask==$FLASK_VERSION"
script: "invoke travisci"
matrix:
  exclude:
      - python: "3.6"
      env: FLASK_VERSION=0.8
      - python: "3.6"
      env: FLASK_VERSION=0.9